#include "../helper.h"
using namespace std;

int anitube(string *domain, string *urlf);
int avast(string *domain, string *urlf);
int avg(string *domain, string *urlf);
int blip(string *domain, string *urlf);
int blogspot(string *domain, string *urlf);
int fbcdn(string *domain, string *urlf);
int ggpht(string *domain, string *urlf);
int globo(string *domain, string *urlf);
int googlesyndication(string *domain, string *urlf);
int gstatic(string *domain, string *urlf);
int kaspersky(string *domain, string *urlf);
int metacafe(string *domain, string *urlf);
int modovideo(string *domain, string *urlf);
int msn(string *domain, string *urlf);
int netflix(string *domain, string *urlf);
int orkut(string *domain, string *urlf);
int phncdn(string *domain, string *urlf);
int photobucket(string *domain, string *urlf);
int pornhub(string *domain, string *urlf);
int porntube(string *domain, string *urlf);
int redtube(string *domain, string *urlf);
int sourceforge(string *domain, string *urlf);
int sun(string *domain, string *urlf);
int terratv(string *domain, string *urlf);
int tumblr(string *domain, string *urlf);
int tvuol(string *domain, string *urlf);
int videobb(string *domain, string *urlf);
int videologtv(string *domain, string *urlf);
int vimeo(string *domain, string *urlf);
int xvideos(string *domain, string *urlf);
int youtube(string *domain, string *urlf);
int ytimg(string *domain, string *urlf);
