#include "../helper.h"
using namespace std;

int anitube(string domain, string url, string *urlf);
int avast(string domain, string url, string *urlf);
int avg(string domain, string url, string *urlf);
int blip(string domain, string url, string *urlf);
int blogspot(string domain, string url, string *urlf);
int fbcdn(string domain, string url, string *urlf);
int ggpht(string domain, string url, string *urlf);
int globo(string domain, string url, string *urlf);
int googlesyndication(string domain, string url, string *urlf);
int gstatic(string domain, string url, string *urlf);
int kaspersky(string domain, string url, string *urlf);
int metacafe(string domain, string url, string *urlf);
int modovideo(string domain, string url, string *urlf);
int msn(string domain, string url, string *urlf);
int netflix(string domain, string url, string *urlf);
int orkut(string domain, string url, string *urlf);
int phncdn(string domain, string url, string *urlf);
int photobucket(string domain, string url, string *urlf);
int pornhub(string domain, string url, string *urlf);
int porntube(string domain, string url, string *urlf);
int redtube(string domain, string url, string *urlf);
int sourceforge(string domain, string url, string *urlf);
int sun(string domain, string url, string *urlf);
int terratv(string domain, string url, string *urlf);
int tumblr(string domain, string url, string *urlf);
int tvuol(string domain, string url, string *urlf);
int videobb(string domain, string url, string *urlf);
int videologtv(string domain, string url, string *urlf);
int vimeo(string domain, string url, string *urlf);
int xvideos(string domain, string url, string *urlf);
int youtube(string domain, string url, string *urlf);
int ytimg(string domain, string url, string *urlf);
